/**
 * GmatScriptGenerator.js — Converts store objects to GMAT script text
 *
 * C++ reference: src/base/interpreter/ScriptInterpreter.cpp
 */

// Hex-to-GMAT color name mapping (from ColorTypes.hpp / ColorDatabase)
const HEX_TO_GMAT_COLOR = {
  '#ff0000':'Red','#008000':'Green','#ffff00':'Yellow','#0000ff':'Blue',
  '#ffc0cb':'Pink','#00ff00':'Lime','#ffd700':'Gold','#000080':'Navy',
  '#800080':'Purple','#808000':'Olive','#f5f5dc':'Beige','#00ffff':'Cyan',
  '#ff00ff':'Fuchsia','#2e8b57':'SeaGreen','#cd853f':'Peru','#6a5acd':'SlateBlue',
  '#da70d6':'Orchid','#00ff7f':'SpringGreen','#d2b48c':'Tan','#40e0d0':'Turquoise',
  '#008080':'Teal','#d3d3d3':'LightGray','#a9a9a9':'DarkGray','#696969':'DimGray',
  '#2f4f4f':'DarkSlateGray','#ff8c00':'Orange','#daa520':'GoldenRod',
  '#ffffff':'White','#000000':'Black','#808080':'Gray','#c0c0c0':'Silver',
  '#a52a2a':'Brown','#800000':'Maroon','#4169e1':'SteelBlue','#87ceeb':'SkyBlue',
  '#add8e6':'LightBlue','#ee82ee':'Violet','#dda0dd':'Plum','#f5deb3':'Wheat',
  '#ff4500':'OrangeRed','#fa8072':'Salmon','#a0522d':'Sienna','#f0e68c':'Khaki',
};

// Spacecraft fields that are not supported in base GMAT (require Attitude plugin or similar)
const SC_SKIP_FIELDS = new Set([
  'AttitudeModel','AttitudeStateType','AttitudeRateStateType','EulerSequence',
  'AttitudeCoordinateSystem','AttitudeRateDisplayStateType',
]);

// Spacecraft state element fields by state type - only output elements matching DisplayStateType
const SC_STATE_ELEMENTS = {
  Keplerian: new Set(['SMA', 'ECC', 'INC', 'RAAN', 'AOP', 'TA', 'MA', 'EA', 'HA']),
  Cartesian: new Set(['X', 'Y', 'Z', 'VX', 'VY', 'VZ']),
  SphericalAZFPA: new Set(['RMAG', 'RA', 'DEC', 'VMAG', 'AZI', 'FPA']),
  SphericalRADEC: new Set(['RMAG', 'RA', 'DEC', 'VMAG', 'RAV', 'DECV']),
  Equinoctial: new Set(['SMA', 'EquinoctialH', 'EquinoctialK', 'EquinoctialP', 'EquinoctialQ', 'MLONG']),
  ModifiedEquinoctial: new Set(['SemilatusRectum', 'ModEquinoctialF', 'ModEquinoctialG', 'ModEquinoctialH', 'ModEquinoctialK', 'TLONG']),
  Delaunay: new Set(['Delaunayl', 'Delaunayg', 'Delaunayh', 'DelaunayL', 'DelaunayG', 'DelaunayH']),
  Planetodetic: new Set(['PlanetodeticRMAG', 'PlanetodeticLON', 'PlanetodeticLAT', 'PlanetodeticVMAG', 'PlanetodeticAZI', 'PlanetodeticHFPA']),
  OutgoingAsymptote: new Set(['OutgoingRadPer', 'OutgoingC3Energy', 'OutgoingRHA', 'OutgoingDHA', 'OutgoingBVAZI', 'TA']),
  IncomingAsymptote: new Set(['IncomingRadPer', 'IncomingC3Energy', 'IncomingRHA', 'IncomingDHA', 'IncomingBVAZI', 'TA']),
  BrouwerMeanShort: new Set(['BrouwerShortSMA', 'BrouwerShortECC', 'BrouwerShortINC', 'BrouwerShortRAAN', 'BrouwerShortAOP', 'BrouwerShortMA']),
  BrouwerMeanLong: new Set(['BrouwerLongSMA', 'BrouwerLongECC', 'BrouwerLongINC', 'BrouwerLongRAAN', 'BrouwerLongAOP', 'BrouwerLongMA']),
};

// Get all state element field names (union of all types)
const ALL_STATE_ELEMENTS = new Set([...Object.values(SC_STATE_ELEMENTS)].flatMap(s => [...s]));

// Fields that use On/Off instead of true/false, keyed by object type
// (some field names like 'Axes' have different meanings for different types)
const ON_OFF_FIELDS = {
  ForceModel: new Set(['SRP', 'RelativisticCorrection']),
  OrbitView: new Set(['Axes', 'Grid', 'SunLine', 'EclipticPlane', 'XYPlane', 'WireFrame',
    'UseInitialView', 'EnableStars', 'EnableConstellations']),
};

// Fields that need quotes around their string values (file paths, identifiers)
const QUOTED_STRING_FIELDS = new Set([
  'ModelFile', 'Id', 'Filename',
  'SPADSRPFile', 'SPADDragFile',
  'AttitudeDisplayStateType', 'AttitudeRateDisplayStateType', 'AttitudeCoordinateSystem',
]);

export class GmatScriptGenerator {
  constructor(store) {
    this.store = store;
  }

  /**
   * Generate script for a single object by name
   * @param {string} objectName - The name of the object
   * @returns {string} The generated script for that object only
   */
  generateForObject(objectName) {
    const obj = this.store.getObject(objectName);
    if (!obj) return `% Object "${objectName}" not found`;

    const lines = [];
    lines.push(`% Resource script for: ${obj.name} (${obj.type})`);
    lines.push('');
    lines.push(...this._genObject(obj));

    // For Propagator, also include its ForceModel
    if (obj.type === 'Propagator' && obj.properties.FM) {
      const fm = this.store.getObject(obj.properties.FM);
      if (fm) {
        lines.push('');
        lines.push(...this._genObject(fm));
      }
    }

    return lines.join('\n');
  }

  generate(sourceName = null) {
    const lines = [];
    lines.push('% Auto-generated by GMAT Web GUI');
    if (sourceName) {
      lines.push(`% Source: ${sourceName}`);
    }
    lines.push('');

    const order = [
      'GroundStation', 'Spacecraft', 'Formation',
      'ChemicalTank', 'ElectricTank', 'ChemicalThruster', 'ElectricThruster',
      'SolarPowerSystem', 'NuclearPowerSystem',
      'ForceModel', 'Propagator',
      'ImpulsiveBurn', 'FiniteBurn',
      'DifferentialCorrector', 'VF13ad',
      'CoordinateSystem',
      'ReportFile', 'OrbitView', 'XYPlot', 'EphemerisFile',
      'Variable', 'Array', 'String',
      'FileInterface',
      'EclipseLocator', 'ContactLocator',
      'GmatFunction',
    ];

    for (const type of order) {
      const objs = this.store.getAllByType(type);
      if (objs.length === 0) continue;
      lines.push('%' + '-'.repeat(40));
      lines.push(`%---------- ${type}`);
      lines.push('%' + '-'.repeat(40));
      lines.push('');
      for (const obj of objs) {
        lines.push(...this._genObject(obj));
        lines.push('');
      }
    }

    lines.push('%' + '-'.repeat(40));
    lines.push('%---------- Mission Sequence');
    lines.push('%' + '-'.repeat(40));
    lines.push('');
    lines.push('BeginMissionSequence;');
    lines.push('');
    for (const cmd of this.store.missionSequence) {
      lines.push(this._genCommand(cmd));
    }

    return lines.join('\n');
  }

  _genObject(obj) {
    const lines = [];
    lines.push(`Create ${obj.type} ${obj.name};`);
    const p = obj.properties;

    // For ForceModel, filter PointMasses to exclude bodies already in PrimaryBodies
    // (GMAT doesn't allow a body to have both GravityField and PointMassForce)
    let filteredPointMasses = null;
    if (obj.type === 'ForceModel' && Array.isArray(p.PointMasses) && Array.isArray(p.PrimaryBodies)) {
      const primarySet = new Set(p.PrimaryBodies);
      filteredPointMasses = p.PointMasses.filter(body => !primarySet.has(body));
    }

    for (const [key, value] of Object.entries(p)) {
      if (value === undefined || value === null) continue;
      // Skip empty strings (would produce invalid "GMAT X.Y = ;")
      if (typeof value === 'string' && value === '') continue;
      // Skip empty arrays
      if (Array.isArray(value) && value.length === 0) continue;
      // For ForceModel PointMasses, use filtered list that excludes PrimaryBodies
      if (obj.type === 'ForceModel' && key === 'PointMasses' && filteredPointMasses !== null) {
        if (filteredPointMasses.length === 0) continue; // Skip if empty after filtering
        lines.push(`GMAT ${obj.name}.${key} = ${this._fmt(filteredPointMasses)};`);
        continue;
      }
      // Skip attitude fields not supported in WASM build
      if (obj.type === 'Spacecraft' && SC_SKIP_FIELDS.has(key)) continue;
      // Skip state elements that don't match the current DisplayStateType
      if (obj.type === 'Spacecraft' && ALL_STATE_ELEMENTS.has(key)) {
        const stateType = p.DisplayStateType || 'Keplerian';
        const allowedElements = SC_STATE_ELEMENTS[stateType] || SC_STATE_ELEMENTS.Keplerian;
        if (!allowedElements.has(key)) continue;
      }
      // Convert hex color to GMAT name
      if ((key === 'OrbitColor' || key === 'TargetColor') && typeof value === 'string' && value.startsWith('#')) {
        const gmatName = HEX_TO_GMAT_COLOR[value.toLowerCase()];
        if (gmatName) {
          lines.push(`GMAT ${obj.name}.${key} = ${gmatName};`);
        } else {
          // Convert hex to GMAT integer format (0xBBGGRR)
          const r = parseInt(value.slice(1,3), 16);
          const g = parseInt(value.slice(3,5), 16);
          const b = parseInt(value.slice(5,7), 16);
          lines.push(`GMAT ${obj.name}.${key} = [${r} ${g} ${b}];`);
        }
        continue;
      }
      // ForceModel nested props - only allow supported ones
      if (obj.type === 'ForceModel' && (key.startsWith('GravityField.') || key.startsWith('Drag.'))) {
        // String values in nested props need quotes (PotentialFile, TideModel, AtmosphereModel)
        if (typeof value === 'string' && isNaN(Number(value))) {
          lines.push(`GMAT ${obj.name}.${key} = '${value}';`);
        } else {
          lines.push(`GMAT ${obj.name}.${key} = ${this._fmt(value)};`);
        }
        continue;
      }
      // Skip invalid ForceModel SRP nested properties (not supported in GMAT syntax)
      if (obj.type === 'ForceModel' && key.startsWith('SRP.')) {
        continue;
      }
      // Fields that use On/Off instead of true/false (type-specific)
      const typeOnOffFields = ON_OFF_FIELDS[obj.type];
      if (typeOnOffFields && typeOnOffFields.has(key)) {
        const v = (value === true || value === 'true' || value === 'On' || value === 'on') ? 'On' : 'Off';
        lines.push(`GMAT ${obj.name}.${key} = ${v};`);
        continue;
      }
      // Fields that need quotes around string values (paths, identifiers)
      if (QUOTED_STRING_FIELDS.has(key) && typeof value === 'string' && value !== '') {
        lines.push(`GMAT ${obj.name}.${key} = '${value}';`);
        continue;
      }
      lines.push(`GMAT ${obj.name}.${key} = ${this._fmt(value)};`);
    }
    return lines;
  }

  _fmt(value) {
    if (Array.isArray(value)) return `{${value.join(', ')}}`;
    if (typeof value === 'boolean') return value ? 'true' : 'false';
    // Don't quote strings that look like arrays (e.g., "[ true true ]" from imported scripts)
    if (typeof value === 'string' && value.startsWith('[')) return value;
    if (typeof value === 'string' && value.includes(' ')) return `'${value}'`;
    return String(value);
  }

  _genCommand(cmd) {
    switch (cmd.type) {
      case 'Propagate': {
        const spacecraft = Array.isArray(cmd.spacecraft) ? cmd.spacecraft : [cmd.spacecraft];
        const param = cmd.stopCondition.param;
        // Event conditions like Periapsis, Apoapsis don't take a value
        const isEventCondition = /\.(Periapsis|Apoapsis)$/.test(param);
        const stopStr = isEventCondition ? param : `${param} = ${cmd.stopCondition.value}`;
        // Use Synchronized syntax for multiple spacecraft (required for finite burns)
        if (spacecraft.length > 1) {
          const propCalls = spacecraft.map(sc => `${cmd.propagator}(${sc})`).join(' ');
          return `Propagate Synchronized ${propCalls} {${stopStr}};`;
        }
        return `Propagate ${cmd.propagator}(${spacecraft[0]}) {${stopStr}};`;
      }
      case 'Maneuver':
        return `Maneuver ${cmd.burn}(${cmd.spacecraft});`;
      case 'Report': {
        const params = (cmd.parameters || []).join(' ');
        return `Report ${cmd.reportFile} ${params};`;
      }
      case 'Target':
        return `Target ${cmd.solver || 'DC'};`;
      case 'EndTarget':
        return 'EndTarget;';
      case 'Vary':
        return `Vary ${cmd.solver || 'DC'}(${cmd.variable || ''} = ${cmd.initialValue || 0}, {Perturbation = ${cmd.perturbation || 0.0001}, Lower = ${cmd.lower || -9.999e300}, Upper = ${cmd.upper || 9.999e300}, MaxStep = ${cmd.maxStep || 0.1}});`;
      case 'Achieve':
        return `Achieve ${cmd.solver || 'DC'}(${cmd.goal || ''} = ${cmd.value || 0}, {Tolerance = ${cmd.tolerance || 0.1}});`;
      case 'Optimize':
        return `Optimize ${cmd.solver || 'VF13ad'};`;
      case 'EndOptimize':
        return 'EndOptimize;';
      case 'Minimize':
        return `Minimize ${cmd.solver || 'VF13ad'}(${cmd.objective || ''});`;
      case 'NonlinearConstraint':
        return `NonlinearConstraint ${cmd.solver || 'VF13ad'}(${cmd.constraint || ''} ${cmd.comparator || '>='} ${cmd.value || 0});`;
      case 'BeginFiniteBurn':
        return `BeginFiniteBurn ${cmd.burn}(${cmd.spacecraft});`;
      case 'EndFiniteBurn':
        return `EndFiniteBurn ${cmd.burn}(${cmd.spacecraft});`;
      case 'If':
        return `If ${cmd.condition || 'true'};`;
      case 'Else':
        return 'Else;';
      case 'EndIf':
        return 'EndIf;';
      case 'For':
        return `For ${cmd.variable || 'I'} = ${cmd.start || 1}:${cmd.step || 1}:${cmd.end || 10};`;
      case 'EndFor':
        return 'EndFor;';
      case 'While':
        return `While ${cmd.condition || 'true'};`;
      case 'EndWhile':
        return 'EndWhile;';
      case 'Assignment':
        return `GMAT ${cmd.lhs || ''} = ${cmd.rhs || ''};`;
      case 'Toggle':
        return `Toggle ${cmd.subscriber || ''} ${cmd.state || 'On'};`;
      case 'PenUp':
        return `PenUp ${cmd.subscriber || ''};`;
      case 'PenDown':
        return `PenDown ${cmd.subscriber || ''};`;
      case 'MarkPoint':
        return `MarkPoint ${cmd.subscriber || ''};`;
      case 'ClearPlot':
        return `ClearPlot ${cmd.subscriber || ''};`;
      case 'Stop':
        return 'Stop;';
      case 'BeginScript':
        return `BeginScript;\n${cmd.script || ''}\nEndScript;`;
      default:
        return `% Unknown command: ${cmd.type}`;
    }
  }
}
