/**
 * YamlMissionConverter.js - Converts YAML mission definitions to GMAT scripts
 *
 * Conversion flow:
 *   YAML object -> GmatObjectStore -> GmatScriptGenerator -> GMAT script text
 *
 * The converter reuses GmatScriptGenerator for the final step, ensuring
 * consistency with scripts generated by the GUI.
 *
 * C++ reference: src/base/interpreter/ScriptInterpreter.cpp
 */

import { GmatObjectStore } from '../executive/GmatObjectStore.js';
import { GmatScriptGenerator } from './GmatScriptGenerator.js';

export class YamlMissionConverter {
  constructor() {
    this.store = new GmatObjectStore();
    this.errors = [];
    this.warnings = [];
  }

  /**
   * Convert parsed YAML object to GMAT script
   * @param {object} yamlObj - Parsed YAML object (from js-yaml)
   * @returns {{script: string, errors: string[], warnings: string[]}}
   */
  convert(yamlObj) {
    this.errors = [];
    this.warnings = [];
    this.store.clearAll();

    try {
      // Phase 1: Populate store from YAML (in dependency order)
      this._processResources(yamlObj.resources || {});
      this._processMissionSequence(yamlObj.missionSequence || []);

      // Validate all references
      this._validateReferences();

      if (this.errors.length > 0) {
        return {
          script: '',
          errors: this.errors,
          warnings: this.warnings
        };
      }

      // Phase 2: Generate script using existing generator
      const generator = new GmatScriptGenerator(this.store);
      const script = generator.generate(yamlObj.name || 'YAML Mission');

      return {
        script,
        errors: this.errors,
        warnings: this.warnings
      };
    } catch (e) {
      this.errors.push(`Conversion failed: ${e.message}`);
      return {
        script: '',
        errors: this.errors,
        warnings: this.warnings
      };
    }
  }

  /**
   * Process all resources in dependency order
   */
  _processResources(resources) {
    // Hardware first (tanks before thrusters)
    // Support both resources.hardware.tanks and resources.tanks (legacy)
    const hardware = resources.hardware || {};
    this._processTanks(hardware.tanks || resources.tanks || {});
    this._processThrusters(hardware.thrusters || resources.thrusters || {});
    this._processPowerSystems(hardware.powerSystems || resources.powerSystems || {});

    // Spacecraft (references hardware)
    this._processSpacecraft(resources.spacecraft || {});

    // Force models and propagators
    this._processForceModels(resources.forceModels || {});
    this._processPropagators(resources.propagators || {});

    // Burns (reference thrusters)
    this._processBurns(resources.burns || {});

    // Solvers
    this._processSolvers(resources.solvers || {});

    // Subscribers
    this._processSubscribers(resources.subscribers || {});

    // Variables
    this._processVariables(resources.variables || {});

    // Coordinate systems
    this._processCoordinateSystems(resources.coordinateSystems || {});

    // Ground stations
    this._processGroundStations(resources.groundStations || {});
  }

  /**
   * Process tanks (ChemicalTank, ElectricTank)
   */
  _processTanks(tanks) {
    for (const [name, config] of Object.entries(tanks)) {
      const type = config.type || 'ChemicalTank';
      const obj = this.store.createObject(type, name);

      // Copy all properties except 'type'
      for (const [key, value] of Object.entries(config)) {
        if (key !== 'type') {
          obj.properties[key] = value;
        }
      }
    }
  }

  /**
   * Process thrusters (ChemicalThruster, ElectricThruster)
   */
  _processThrusters(thrusters) {
    for (const [name, config] of Object.entries(thrusters)) {
      const type = config.type || 'ChemicalThruster';
      const obj = this.store.createObject(type, name);

      for (const [key, value] of Object.entries(config)) {
        if (key === 'type') continue;

        // Handle Tank reference - can be string or array
        if (key === 'Tank') {
          obj.properties.Tank = Array.isArray(value) ? value : [value];
          continue;
        }

        // Handle shorthand direction array (ThrustDirection or direction)
        if ((key === 'ThrustDirection' || key === 'direction') && Array.isArray(value)) {
          obj.properties.ThrustDirection1 = value[0] || 0;
          obj.properties.ThrustDirection2 = value[1] || 0;
          obj.properties.ThrustDirection3 = value[2] || 0;
          continue;
        }

        // Handle C polynomial array (thrust coefficients)
        if (key === 'C' && Array.isArray(value)) {
          for (let i = 0; i < 16; i++) {
            obj.properties[`C${i + 1}`] = value[i] || 0;
          }
          continue;
        }

        // Handle K polynomial array (Isp coefficients)
        if (key === 'K' && Array.isArray(value)) {
          for (let i = 0; i < 16; i++) {
            obj.properties[`K${i + 1}`] = value[i] || 0;
          }
          continue;
        }

        obj.properties[key] = value;
      }
    }
  }

  /**
   * Process power systems (SolarPowerSystem, NuclearPowerSystem)
   */
  _processPowerSystems(powerSystems) {
    for (const [name, config] of Object.entries(powerSystems)) {
      const type = config.type || 'SolarPowerSystem';
      const obj = this.store.createObject(type, name);

      for (const [key, value] of Object.entries(config)) {
        if (key !== 'type') {
          obj.properties[key] = value;
        }
      }
    }
  }

  /**
   * Process spacecraft with structured state/mass/hardware
   */
  _processSpacecraft(spacecraft) {
    for (const [name, config] of Object.entries(spacecraft)) {
      if (name.startsWith('_')) continue; // Skip meta keys

      const obj = this.store.createObject('Spacecraft', name);

      // Process epoch
      if (config.epoch) {
        if (config.epoch.format) obj.properties.DateFormat = config.epoch.format;
        // Quote epoch value as GMAT expects (e.g., '21545')
        if (config.epoch.value !== undefined) obj.properties.Epoch = `'${config.epoch.value}'`;
      }

      // Process state
      if (config.state) {
        if (config.state.type) obj.properties.DisplayStateType = config.state.type;
        if (config.state.coordinateSystem) obj.properties.CoordinateSystem = config.state.coordinateSystem;

        // Handle shorthand position array [X, Y, Z]
        if (config.state.position && Array.isArray(config.state.position)) {
          obj.properties.X = config.state.position[0] || 0;
          obj.properties.Y = config.state.position[1] || 0;
          obj.properties.Z = config.state.position[2] || 0;
        }

        // Handle shorthand velocity array [VX, VY, VZ]
        if (config.state.velocity && Array.isArray(config.state.velocity)) {
          obj.properties.VX = config.state.velocity[0] || 0;
          obj.properties.VY = config.state.velocity[1] || 0;
          obj.properties.VZ = config.state.velocity[2] || 0;
        }

        // Copy state elements (SMA, ECC, X, Y, etc.) - individual props override arrays
        const stateProps = [
          'SMA', 'ECC', 'INC', 'RAAN', 'AOP', 'TA', 'MA', 'EA', 'HA',
          'X', 'Y', 'Z', 'VX', 'VY', 'VZ',
          'RMAG', 'RA', 'DEC', 'VMAG', 'AZI', 'FPA', 'RAV', 'DECV'
        ];
        for (const prop of stateProps) {
          if (config.state[prop] !== undefined) {
            obj.properties[prop] = config.state[prop];
          }
        }
      }

      // Process mass
      if (config.mass) {
        if (config.mass.dry !== undefined) obj.properties.DryMass = config.mass.dry;
      }

      // Process aero properties
      if (config.aero) {
        for (const [key, value] of Object.entries(config.aero)) {
          obj.properties[key] = value;
        }
      }

      // Process spad (Solar Pressure and Drag) properties
      if (config.spad) {
        if (config.spad.aero) {
          if (config.spad.aero.Cd !== undefined) obj.properties.Cd = config.spad.aero.Cd;
          if (config.spad.aero.DragArea !== undefined) obj.properties.DragArea = config.spad.aero.DragArea;
          if (config.spad.aero.DragScaleFactor !== undefined) obj.properties.SPADDragScaleFactor = config.spad.aero.DragScaleFactor;
          if (config.spad.aero.DragInterpolationMethod !== undefined) obj.properties.SPADDragInterpolationMethod = config.spad.aero.DragInterpolationMethod;
        }
        if (config.spad.solar) {
          if (config.spad.solar.Cr !== undefined) obj.properties.Cr = config.spad.solar.Cr;
          if (config.spad.solar.SRPArea !== undefined) obj.properties.SRPArea = config.spad.solar.SRPArea;
          if (config.spad.solar.SRPScaleFactor !== undefined) obj.properties.SPADSRPScaleFactor = config.spad.solar.SRPScaleFactor;
          if (config.spad.solar.SRPInterpolationMethod !== undefined) obj.properties.SPADSRPInterpolationMethod = config.spad.solar.SRPInterpolationMethod;
        }
      }

      // Process hardware references
      if (config.hardware) {
        if (config.hardware.tanks) obj.properties.Tanks = config.hardware.tanks;
        if (config.hardware.thrusters) obj.properties.Thrusters = config.hardware.thrusters;
        if (config.hardware.powerSystem) obj.properties.PowerSystem = config.hardware.powerSystem;
      }

      // Process display (model, orbitColor, targetColor)
      if (config.display) {
        if (config.display.orbitColor) obj.properties.OrbitColor = config.display.orbitColor;
        if (config.display.targetColor) obj.properties.TargetColor = config.display.targetColor;
        if (config.display.model) {
          const model = config.display.model;
          if (model.file) obj.properties.ModelFile = model.file;
          if (model.offsets) {
            if (model.offsets.x !== undefined) obj.properties.ModelOffsetX = model.offsets.x;
            if (model.offsets.y !== undefined) obj.properties.ModelOffsetY = model.offsets.y;
            if (model.offsets.z !== undefined) obj.properties.ModelOffsetZ = model.offsets.z;
          }
          if (model.rotations) {
            if (model.rotations.x !== undefined) obj.properties.ModelRotationX = model.rotations.x;
            if (model.rotations.y !== undefined) obj.properties.ModelRotationY = model.rotations.y;
            if (model.rotations.z !== undefined) obj.properties.ModelRotationZ = model.rotations.z;
          }
          if (model.scale !== undefined) obj.properties.ModelScale = model.scale;
        }
      }

      // Process attitude
      if (config.attitude) {
        if (config.attitude.model) obj.properties.Attitude = config.attitude.model;
        if (config.attitude.displayStateType) obj.properties.AttitudeDisplayStateType = config.attitude.displayStateType;
        if (config.attitude.eulerSequence) obj.properties.EulerAngleSequence = config.attitude.eulerSequence;
        if (config.attitude.eulerAngle1 !== undefined) obj.properties.EulerAngle1 = config.attitude.eulerAngle1;
        if (config.attitude.eulerAngle2 !== undefined) obj.properties.EulerAngle2 = config.attitude.eulerAngle2;
        if (config.attitude.eulerAngle3 !== undefined) obj.properties.EulerAngle3 = config.attitude.eulerAngle3;
      }

      // Process EulerAngles shorthand - only set EulerAngleSequence (not individual angles)
      if (config.EulerAngles && typeof config.EulerAngles === 'object') {
        // Quote EulerAngleSequence value as GMAT expects (e.g., '321')
        if (config.EulerAngles.sequence) obj.properties.EulerAngleSequence = `'${config.EulerAngles.sequence}'`;
        // Clear the default angle values set by GmatDefaults (we don't want them in output)
        delete obj.properties.EulerAngle1;
        delete obj.properties.EulerAngle2;
        delete obj.properties.EulerAngle3;
        delete obj.properties.EulerAngleRate1;
        delete obj.properties.EulerAngleRate2;
        delete obj.properties.EulerAngleRate3;
      }

      // Clear SPAD default properties that weren't explicitly set in YAML
      if (!config.spad?.aero?.DragInterpolationMethod) {
        delete obj.properties.SPADDragInterpolationMethod;
      }
      if (!config.spad?.aero?.DragScaleFactor) {
        delete obj.properties.SPADDragScaleFactor;
      }
      if (!config.spad?.solar?.SRPInterpolationMethod) {
        delete obj.properties.SPADSRPInterpolationMethod;
      }

      // Copy any remaining direct properties
      const structuredKeys = ['epoch', 'state', 'mass', 'aero', 'spad', 'hardware', 'display', 'attitude', 'EulerAngles'];
      for (const [key, value] of Object.entries(config)) {
        if (!structuredKeys.includes(key)) {
          obj.properties[key] = value;
        }
      }
    }
  }

  /**
   * Process force models
   */
  _processForceModels(forceModels) {
    for (const [name, config] of Object.entries(forceModels)) {
      const obj = this.store.createObject('ForceModel', name);

      // Check if gravityField is explicitly specified in YAML
      const hasGravityField = 'gravityField' in config;

      for (const [key, value] of Object.entries(config)) {
        // Handle shorthand for SRP/RelativisticCorrection booleans
        if (key === 'SRP' || key === 'RelativisticCorrection') {
          obj.properties[key] = value === true ? 'On' : (value === false ? 'Off' : value);
          continue;
        }

        // Map PrimaryBodies to PointMasses (GMAT uses PointMasses for simple point mass gravity)
        if (key === 'PrimaryBodies') {
          obj.properties.PointMasses = value;
          obj.properties.PrimaryBodies = []; // Clear default to prevent conflict
          continue;
        }

        // When using PointMasses directly, clear PrimaryBodies default
        if (key === 'PointMasses') {
          obj.properties.PointMasses = value;
          obj.properties.PrimaryBodies = []; // Clear default to prevent conflict
          continue;
        }

        // Handle nested gravity field properties (for full gravity models)
        if (key === 'gravityField' && typeof value === 'object') {
          for (const [body, props] of Object.entries(value)) {
            if (props.Degree !== undefined) obj.properties[`GravityField.${body}.Degree`] = props.Degree;
            if (props.Order !== undefined) obj.properties[`GravityField.${body}.Order`] = props.Order;
            if (props.PotentialFile !== undefined) obj.properties[`GravityField.${body}.PotentialFile`] = props.PotentialFile;
          }
          continue;
        }

        // Handle drag
        if (key === 'drag' && typeof value === 'object') {
          if (value.model) obj.properties['Drag.AtmosphereModel'] = value.model;
          if (value.F107) obj.properties['Drag.F107'] = value.F107;
          if (value.F107A) obj.properties['Drag.F107A'] = value.F107A;
          if (value.MagneticIndex) obj.properties['Drag.MagneticIndex'] = value.MagneticIndex;
          continue;
        }

        obj.properties[key] = value;
      }

      // Clear GravityField defaults if not explicitly specified in YAML
      // (When using PointMasses alone, we don't want GravityField properties)
      if (!hasGravityField) {
        // Remove any GravityField.* properties that may have been set by defaults
        for (const key of Object.keys(obj.properties)) {
          if (key.startsWith('GravityField.')) {
            delete obj.properties[key];
          }
        }
      }
    }
  }

  /**
   * Process propagators
   */
  _processPropagators(propagators) {
    for (const [name, config] of Object.entries(propagators)) {
      const obj = this.store.createObject('Propagator', name);

      for (const [key, value] of Object.entries(config)) {
        obj.properties[key] = value;
      }
    }
  }

  /**
   * Process burns (ImpulsiveBurn, FiniteBurn)
   */
  _processBurns(burns) {
    for (const [name, config] of Object.entries(burns)) {
      const type = config.type || 'ImpulsiveBurn';
      const obj = this.store.createObject(type, name);

      for (const [key, value] of Object.entries(config)) {
        if (key === 'type') continue;

        // Handle shorthand elements array for ImpulsiveBurn
        if (key === 'elements' && Array.isArray(value)) {
          obj.properties.Element1 = value[0] || 0;
          obj.properties.Element2 = value[1] || 0;
          obj.properties.Element3 = value[2] || 0;
          continue;
        }

        // Quote ThrottleLogicAlgorithm as GMAT expects (e.g., 'MaxNumberOfThrusters')
        if (key === 'ThrottleLogicAlgorithm') {
          obj.properties[key] = `'${value}'`;
          continue;
        }

        obj.properties[key] = value;
      }
    }
  }

  /**
   * Process solvers (DifferentialCorrector, VF13ad)
   */
  _processSolvers(solvers) {
    for (const [name, config] of Object.entries(solvers)) {
      const type = config.type || 'DifferentialCorrector';
      const obj = this.store.createObject(type, name);

      for (const [key, value] of Object.entries(config)) {
        if (key !== 'type') {
          obj.properties[key] = value;
        }
      }
    }
  }

  /**
   * Process subscribers (ReportFile, OrbitView, XYPlot, EphemerisFile)
   */
  _processSubscribers(subscribers) {
    // Fields that should use GMAT's bracket array format: [ x y z ]
    const bracketArrayFields = new Set([
      'DrawObject', 'Size', 'UpperLeft', 'ViewPointVector'
    ]);

    for (const [name, config] of Object.entries(subscribers)) {
      const type = config.type || 'ReportFile';
      const obj = this.store.createObject(type, name);

      for (const [key, value] of Object.entries(config)) {
        if (key === 'type') continue;

        // Handle boolean to On/Off conversion for OrbitView
        if (type === 'OrbitView' && typeof value === 'boolean') {
          const onOffFields = ['Axes', 'Grid', 'SunLine', 'EclipticPlane', 'XYPlane', 'WireFrame',
            'UseInitialView', 'EnableStars', 'EnableConstellations'];
          if (onOffFields.includes(key)) {
            obj.properties[key] = value ? 'On' : 'Off';
            continue;
          }
        }

        // Convert arrays to GMAT bracket format: [ x y z ] for specific fields
        if (bracketArrayFields.has(key) && Array.isArray(value)) {
          obj.properties[key] = `[ ${value.join(' ')} ]`;
          continue;
        }

        obj.properties[key] = value;
      }
    }
  }

  /**
   * Process variables (Variable, Array, String)
   */
  _processVariables(variables) {
    for (const [name, config] of Object.entries(variables)) {
      const type = config.type || 'Variable';
      const obj = this.store.createObject(type, name);

      for (const [key, value] of Object.entries(config)) {
        if (key !== 'type') {
          obj.properties[key] = value;
        }
      }
    }
  }

  /**
   * Process coordinate systems
   */
  _processCoordinateSystems(coordinateSystems) {
    for (const [name, config] of Object.entries(coordinateSystems)) {
      const obj = this.store.createObject('CoordinateSystem', name);

      for (const [key, value] of Object.entries(config)) {
        obj.properties[key] = value;
      }
    }
  }

  /**
   * Process ground stations
   */
  _processGroundStations(groundStations) {
    for (const [name, config] of Object.entries(groundStations)) {
      const obj = this.store.createObject('GroundStation', name);

      // Handle shorthand location array
      if (config.location && Array.isArray(config.location)) {
        obj.properties.Location1 = config.location[0] || 0;
        obj.properties.Location2 = config.location[1] || 0;
        obj.properties.Location3 = config.location[2] || 0;
      }

      for (const [key, value] of Object.entries(config)) {
        if (key === 'location') continue;
        obj.properties[key] = value;
      }
    }
  }

  /**
   * Process mission sequence commands
   */
  _processMissionSequence(sequence) {
    for (const cmd of sequence) {
      this._processCommand(cmd);
    }
  }

  /**
   * Process a single mission sequence command
   */
  _processCommand(cmd) {
    const type = Object.keys(cmd)[0];
    const config = cmd[type];

    switch (type) {
      case 'propagate':
        this.store.addCommand({
          type: 'Propagate',
          label: config.label,
          propagator: config.propagator,
          spacecraft: config.spacecraft,
          stopCondition: this._parseStopCondition(config.stop, config.spacecraft)
        });
        break;

      case 'maneuver':
        this.store.addCommand({
          type: 'Maneuver',
          label: config.label,
          burn: config.burn,
          spacecraft: config.spacecraft
        });
        break;

      case 'beginFiniteBurn':
        this.store.addCommand({
          type: 'BeginFiniteBurn',
          label: config.label,
          burn: config.burn,
          spacecraft: config.spacecraft
        });
        break;

      case 'endFiniteBurn':
        this.store.addCommand({
          type: 'EndFiniteBurn',
          label: config.label,
          burn: config.burn,
          spacecraft: config.spacecraft
        });
        break;

      case 'target':
        this.store.addCommand({ type: 'Target', solver: config.solver });
        if (config.steps) {
          for (const step of config.steps) {
            this._processCommand(step);
          }
        }
        this.store.addCommand({ type: 'EndTarget' });
        break;

      case 'vary':
        this.store.addCommand({
          type: 'Vary',
          solver: config.solver,
          variable: config.variable,
          initialValue: config.initial || config.initialValue || 0,
          perturbation: config.perturbation || 0.0001,
          lower: config.lower || -9.999e300,
          upper: config.upper || 9.999e300,
          maxStep: config.maxStep || 0.1
        });
        break;

      case 'achieve':
        this.store.addCommand({
          type: 'Achieve',
          solver: config.solver,
          goal: config.goal,
          value: config.value,
          tolerance: config.tolerance || 0.1
        });
        break;

      case 'optimize':
        this.store.addCommand({ type: 'Optimize', solver: config.solver });
        if (config.steps) {
          for (const step of config.steps) {
            this._processCommand(step);
          }
        }
        this.store.addCommand({ type: 'EndOptimize' });
        break;

      case 'minimize':
        this.store.addCommand({
          type: 'Minimize',
          solver: config.solver,
          objective: config.objective
        });
        break;

      case 'nonlinearConstraint':
        this.store.addCommand({
          type: 'NonlinearConstraint',
          solver: config.solver,
          constraint: config.constraint,
          comparator: config.comparator || '>=',
          value: config.value
        });
        break;

      case 'if':
        this.store.addCommand({ type: 'If', condition: config.condition });
        if (config.then) {
          for (const step of config.then) {
            this._processCommand(step);
          }
        }
        if (config.else) {
          this.store.addCommand({ type: 'Else' });
          for (const step of config.else) {
            this._processCommand(step);
          }
        }
        this.store.addCommand({ type: 'EndIf' });
        break;

      case 'for':
        this.store.addCommand({
          type: 'For',
          variable: config.variable,
          start: config.start || 1,
          step: config.step || 1,
          end: config.end || 10
        });
        if (config.body) {
          for (const step of config.body) {
            this._processCommand(step);
          }
        }
        this.store.addCommand({ type: 'EndFor' });
        break;

      case 'while':
        this.store.addCommand({ type: 'While', condition: config.condition });
        if (config.body) {
          for (const step of config.body) {
            this._processCommand(step);
          }
        }
        this.store.addCommand({ type: 'EndWhile' });
        break;

      case 'report':
        this.store.addCommand({
          type: 'Report',
          reportFile: config.reportFile,
          parameters: config.parameters || []
        });
        break;

      case 'toggle':
        this.store.addCommand({
          type: 'Toggle',
          subscriber: config.subscriber,
          state: config.state || 'On'
        });
        break;

      case 'penUp':
        this.store.addCommand({ type: 'PenUp', subscriber: config.subscriber });
        break;

      case 'penDown':
        this.store.addCommand({ type: 'PenDown', subscriber: config.subscriber });
        break;

      case 'markPoint':
        this.store.addCommand({ type: 'MarkPoint', subscriber: config.subscriber });
        break;

      case 'clearPlot':
        this.store.addCommand({ type: 'ClearPlot', subscriber: config.subscriber });
        break;

      case 'assignment':
        this.store.addCommand({
          type: 'Assignment',
          lhs: config.lhs,
          rhs: config.rhs
        });
        break;

      case 'stop':
        this.store.addCommand({ type: 'Stop' });
        break;

      default:
        this.warnings.push(`Unknown command type: ${type}`);
    }
  }

  /**
   * Parse stop condition from YAML shorthand
   */
  _parseStopCondition(stop, spacecraft) {
    if (!stop) {
      return { param: `${spacecraft}.ElapsedSecs`, value: 0 };
    }

    // Handle array for multiple spacecraft (use first)
    const sc = Array.isArray(spacecraft) ? spacecraft[0] : spacecraft;

    // Elapsed time shortcuts
    if (stop.elapsed) {
      if (stop.elapsed.secs !== undefined) {
        return { param: `${sc}.ElapsedSecs`, value: stop.elapsed.secs };
      }
      if (stop.elapsed.days !== undefined) {
        return { param: `${sc}.ElapsedDays`, value: stop.elapsed.days };
      }
      if (stop.elapsed.hours !== undefined) {
        // Convert hours to seconds for ElapsedSecs
        return { param: `${sc}.ElapsedSecs`, value: stop.elapsed.hours * 3600 };
      }
    }

    // Event conditions (no value)
    if (stop.periapsis) {
      return { param: `${sc}.Periapsis`, value: 0 };
    }
    if (stop.apoapsis) {
      return { param: `${sc}.Apoapsis`, value: 0 };
    }

    // Custom parameter
    if (stop.param) {
      return { param: stop.param, value: stop.value || 0 };
    }

    // Fallback
    return { param: `${sc}.ElapsedSecs`, value: 0 };
  }

  /**
   * Validate all object references
   */
  _validateReferences() {
    // Validate spacecraft references
    for (const obj of this.store.objects.values()) {
      if (obj.type === 'Spacecraft') {
        for (const tank of obj.properties.Tanks || []) {
          if (!this.store.getObject(tank)) {
            this.errors.push(`Spacecraft "${obj.name}": Tank "${tank}" not found`);
          }
        }
        for (const thruster of obj.properties.Thrusters || []) {
          if (!this.store.getObject(thruster)) {
            this.errors.push(`Spacecraft "${obj.name}": Thruster "${thruster}" not found`);
          }
        }
        if (obj.properties.PowerSystem && !this.store.getObject(obj.properties.PowerSystem)) {
          this.errors.push(`Spacecraft "${obj.name}": PowerSystem "${obj.properties.PowerSystem}" not found`);
        }
      }

      // Thruster tank references
      if (obj.type === 'ChemicalThruster' || obj.type === 'ElectricThruster') {
        const tanks = obj.properties.Tank || [];
        const tankList = Array.isArray(tanks) ? tanks : [tanks];
        for (const tank of tankList) {
          if (tank && !this.store.getObject(tank)) {
            this.errors.push(`Thruster "${obj.name}": Tank "${tank}" not found`);
          }
        }
      }

      // Propagator force model reference
      if (obj.type === 'Propagator') {
        const fm = obj.properties.FM;
        if (fm && !this.store.getObject(fm)) {
          this.errors.push(`Propagator "${obj.name}": ForceModel "${fm}" not found`);
        }
      }

      // FiniteBurn thruster references
      if (obj.type === 'FiniteBurn') {
        for (const thruster of obj.properties.Thrusters || []) {
          if (!this.store.getObject(thruster)) {
            this.errors.push(`FiniteBurn "${obj.name}": Thruster "${thruster}" not found`);
          }
        }
      }
    }

    // Validate mission sequence references
    for (const cmd of this.store.missionSequence) {
      if (cmd.propagator && !this.store.getObject(cmd.propagator)) {
        this.errors.push(`Mission sequence: Propagator "${cmd.propagator}" not found`);
      }

      if (cmd.spacecraft) {
        const scList = Array.isArray(cmd.spacecraft) ? cmd.spacecraft : [cmd.spacecraft];
        for (const sc of scList) {
          if (!this.store.getObject(sc)) {
            this.errors.push(`Mission sequence: Spacecraft "${sc}" not found`);
          }
        }
      }

      if (cmd.burn && !this.store.getObject(cmd.burn)) {
        this.errors.push(`Mission sequence: Burn "${cmd.burn}" not found`);
      }

      if (cmd.solver && !this.store.getObject(cmd.solver)) {
        this.errors.push(`Mission sequence: Solver "${cmd.solver}" not found`);
      }

      if (cmd.reportFile && !this.store.getObject(cmd.reportFile)) {
        this.errors.push(`Mission sequence: ReportFile "${cmd.reportFile}" not found`);
      }

      if (cmd.subscriber && !this.store.getObject(cmd.subscriber)) {
        this.errors.push(`Mission sequence: Subscriber "${cmd.subscriber}" not found`);
      }
    }
  }
}
