/**
 * GmatDefaults.js — Default property values for GMAT object types
 *
 * C++ reference: src/base/spacecraft/Spacecraft.cpp
 *                src/base/propagator/Propagator.cpp
 *                src/base/burn/ImpulsiveBurn.cpp
 *                src/base/burn/FiniteBurn.cpp
 *                src/base/subscriber/ReportFile.cpp
 *                src/base/subscriber/OrbitView.cpp
 *                src/base/solver/DifferentialCorrector.cpp
 *                src/base/hardware/ChemicalTank.cpp
 *                src/base/hardware/ChemicalThruster.cpp
 */

export const DEFAULTS = {
  Spacecraft: {
    DateFormat: 'UTCGregorian',
    Epoch: '01 Jan 2024 12:00:00.000',
    CoordinateSystem: 'EarthMJ2000Eq',
    DisplayStateType: 'Keplerian',
    SMA: 7191.938817629013,
    ECC: 0.02454974900598091,
    INC: 12.85008005658097,
    RAAN: 306.6148021947984,
    AOP: 314.1905515359921,
    TA: 99.88774933204886,
    AttitudeModel: 'CoordinateSystemFixed',
    AttitudeCoordinateSystem: 'EarthMJ2000Eq',
    AttitudeStateType: 'EulerAngles',
    AttitudeRateStateType: 'EulerAngleRates',
    EulerAngle1: 0, EulerAngle2: 0, EulerAngle3: 0,
    EulerAngleRate1: 0, EulerAngleRate2: 0, EulerAngleRate3: 0,
    EulerSequence: '321',
    DryMass: 850,
    Cd: 2.2, Cr: 1.8,
    DragArea: 15, SRPArea: 1,
    SPADSRPFile: '', SPADSRPScaleFactor: 1.0, SPADSRPInterpolationMethod: 'Bilinear',
    SPADDragFile: '', SPADDragScaleFactor: 1.0, SPADDragInterpolationMethod: 'Bilinear',
    Tanks: [], Thrusters: [], PowerSystem: '',
    NAIFId: -10002, NAIFIdReferenceFrame: -9002,
    OrbitSpiceKernelName: [], AttitudeSpiceKernelName: [],
    SCClockSpiceKernelName: [], FrameSpiceKernelName: [],
    ModelFile: 'aura.3ds',
    ModelOffsetX: 0, ModelOffsetY: 0, ModelOffsetZ: 0,
    ModelRotationX: 0, ModelRotationY: 0, ModelRotationZ: 0,
    ModelScale: 1.0,
    OrbitColor: '#ff0000', TargetColor: '#008080',
  },
  ForceModel: {
    CentralBody: 'Earth',
    PrimaryBodies: ['Earth'],
    PointMasses: [],
    SRP: 'Off',
    RelativisticCorrection: 'Off',
    ErrorControl: 'RSSStep',
    'GravityField.Earth.Degree': 4,
    'GravityField.Earth.Order': 4,
    'GravityField.Earth.PotentialFile': 'JGM2.cof',
  },
  Propagator: {
    FM: '',
    Type: 'RungeKutta89',
    InitialStepSize: 60,
    Accuracy: 9.999999999999999e-12,
    MinStep: 0.001,
    MaxStep: 2700,
    MaxStepAttempts: 50,
    StopIfAccuracyIsViolated: true,
  },
  ImpulsiveBurn: {
    CoordinateSystem: 'Local',
    Origin: 'Earth',
    Axes: 'VNB',
    Element1: 0, Element2: 0, Element3: 0,
    DecrementMass: false,
    Isp: 300,
    GravitationalAccel: 9.81,
  },
  FiniteBurn: {
    Thrusters: [],
    ThrottleLogicAlgorithm: 'MaxNumberOfThrusters',
  },
  ReportFile: {
    Filename: '/tmp/report.txt',
    Add: [],
    WriteHeaders: true,
    LeftJustify: 'On',
    ZeroFill: 'Off',
    FixedWidth: true,
    Delimiter: ' ',
    ColumnWidth: 23,
    WriteReport: true,
  },
  EphemerisFile: {
    Spacecraft: 'DefaultSC',
    CoordinateSystem: 'EarthMJ2000Eq',
    WriteEphemeris: true,
    Filename: '/tmp/ephemeris.bsp',
    FileFormat: 'SPK',
    Interpolator: 'Hermite',
    InterpolationOrder: 7,
    StepSize: 'IntegratorSteps',
    OutputFormat: 'LittleEndian',
    DistanceUnit: 'Kilometers',
    IncludeEventBoundaries: true,
    EpochFormat: 'UTCGregorian',
    InitialEpoch: 'InitialSpacecraftEpoch',
    FinalEpoch: 'FinalSpacecraftEpoch',
  },
  OrbitView: {
    Add: [],
    CoordinateSystem: 'EarthMJ2000Eq',
    DrawObject: [],
    ViewPointReference: 'Earth',
    ViewPointVector: [0, 0, 120000],
    ViewDirection: 'Earth',
    ViewScaleFactor: 1,
    ShowPlot: true,
    Axes: 'On',
    Grid: 'Off',
    SunLine: 'Off',
    EnableStars: 'On',
    StarCount: 7000,
  },
  XYPlot: {
    XVariable: '',
    YVariables: [],
    ShowGrid: true,
    ShowPlot: true,
  },
  DifferentialCorrector: {
    ShowProgress: true,
    ReportStyle: 'Normal',
    MaximumIterations: 25,
    DerivativeMethod: 'ForwardDifference',
    Algorithm: 'NewtonRaphson',
  },
  VF13ad: {
    ShowProgress: true,
    ReportStyle: 'Normal',
    MaximumIterations: 200,
    Tolerance: 1e-5,
    UseCentralDifferences: false,
  },
  Variable: { Value: 0 },
  Array: { RowCount: 1, ColCount: 1 },
  String: { Value: '' },
  GroundStation: {
    CentralBody: 'Earth',
    StateType: 'Spherical',
    HorizonReference: 'Ellipsoid',
    Location1: 0, Location2: 0, Location3: 0,
    Id: '',
    MinimumElevationAngle: 7.0,
  },
  Formation: { Add: [] },
  CoordinateSystem: { Origin: 'Earth', Axes: 'MJ2000Eq' },
  ChemicalTank: {
    FuelMass: 756,
    Pressure: 1500,
    Temperature: 20,
    RefTemperature: 20,
    Volume: 0.75,
    FuelDensity: 1260,
    PressureModel: 'PressureRegulated',
    AllowNegativeFuelMass: false,
  },
  ElectricTank: {
    FuelMass: 756,
    AllowNegativeFuelMass: false,
  },
  ChemicalThruster: {
    CoordinateSystem: 'Local',
    Origin: 'Earth',
    Axes: 'VNB',
    ThrustDirection1: 1, ThrustDirection2: 0, ThrustDirection3: 0,
    DutyCycle: 1.0,
    ThrustScaleFactor: 1.0,
    DecrementMass: false,
    Tank: '',
    GravitationalAccel: 9.81,
    C1: 10, K1: 300,
  },
  ElectricThruster: {
    CoordinateSystem: 'Local',
    Origin: 'Earth',
    Axes: 'VNB',
    ThrustDirection1: 1, ThrustDirection2: 0, ThrustDirection3: 0,
    DutyCycle: 1.0,
    ThrustScaleFactor: 1.0,
    DecrementMass: false,
    Tank: '',
    ThrustModel: 'ConstantThrustAndIsp',
    MaximumUsablePower: 7.266,
    MinimumUsablePower: 0.638,
    ConstantThrust: 0.01,
    Isp: 3000,
    GravitationalAccel: 9.81,
    FixedEfficiency: 0.7,
  },
  SolarPowerSystem: {
    EpochFormat: 'UTCGregorian',
    InitialEpoch: '01 Jan 2000 11:59:28.000',
    InitialMaxPower: 1.2,
    AnnualDecayRate: 5,
    Margin: 5,
    BusCoeff1: 0.3, BusCoeff2: 0, BusCoeff3: 0,
    ShadowModel: 'DualCone',
    ShadowBodies: ['Earth'],
  },
  NuclearPowerSystem: {
    EpochFormat: 'UTCGregorian',
    InitialEpoch: '01 Jan 2000 11:59:28.000',
    InitialMaxPower: 1.2,
    AnnualDecayRate: 5,
    Margin: 5,
    BusCoeff1: 0.3, BusCoeff2: 0, BusCoeff3: 0,
  },
  FileInterface: { Filename: '', Format: 'TextFile' },
  EclipseLocator: {
    Spacecraft: '',
    OccultingBodies: ['Luna'],
    InputEpochFormat: 'UTCGregorian',
    InitialEpoch: '01 Jan 2024 00:00:00.000',
    FinalEpoch: '01 Jan 2024 12:00:00.000',
    StepSize: 10,
    EclipseTypes: ['Umbra', 'Penumbra', 'Antumbra'],
  },
  ContactLocator: {
    Target: '',
    Observer: '',
    LightTimeDirection: 'Transmit',
    InputEpochFormat: 'UTCGregorian',
    InitialEpoch: '01 Jan 2024 00:00:00.000',
    FinalEpoch: '01 Jan 2024 12:00:00.000',
    StepSize: 10,
  },
  GmatFunction: { FunctionPath: '' },
};

export const NAME_PREFIX = {
  Spacecraft: 'Spacecraft',
  Formation: 'Formation',
  ForceModel: 'FM',
  Propagator: 'Prop',
  ImpulsiveBurn: 'ImpBurn',
  FiniteBurn: 'FinBurn',
  DifferentialCorrector: 'DC',
  VF13ad: 'VF13ad',
  ReportFile: 'DefaultReport',
  OrbitView: 'OrbitView',
  XYPlot: 'XYPlot',
  EphemerisFile: 'EphemFile',
  Variable: 'Var',
  Array: 'Arr',
  String: 'Str',
  GroundStation: 'GndStn',
  CoordinateSystem: 'CoordSys',
  ChemicalTank: 'ChemTank',
  ElectricTank: 'ElecTank',
  ChemicalThruster: 'ChemThruster',
  ElectricThruster: 'ElecThruster',
  SolarPowerSystem: 'SolarPower',
  NuclearPowerSystem: 'NuclearPower',
  FileInterface: 'FileInterface',
  EclipseLocator: 'EclLocator',
  ContactLocator: 'ContLocator',
  GmatFunction: 'GmatFunc',
};
