# GMAT WebAssembly CMake cache/options file
#
# This file is loaded via CMake's -C flag to set initial cache values
# for building GMAT with Emscripten. The actual toolchain file is
# provided by Emscripten via emcmake.
#
# Usage:
#   emcmake cmake -C /path/to/emscripten.cmake -S <gmat_root> -B <build_dir>

# Force all libraries to build as STATIC (WASM has no dynamic linking)
SET(BUILD_SHARED_LIBS OFF CACHE BOOL "Build static libraries for WASM" FORCE)

# Disable GUI (no windowing system in WASM)
SET(GMAT_INCLUDE_GUI OFF CACHE BOOL "" FORCE)

# Disable optional subsystems not needed for WASM console
SET(GMAT_INCLUDE_CSALT OFF CACHE BOOL "" FORCE)
SET(GMAT_INCLUDE_API OFF CACHE BOOL "" FORCE)

# Disable all plugins (they use dynamic loading which WASM doesn't support)
SET(PLUGIN_CINTERFACE OFF CACHE BOOL "" FORCE)
SET(PLUGIN_DATAINTERFACE OFF CACHE BOOL "" FORCE)
SET(PLUGIN_DATACALLBACK OFF CACHE BOOL "" FORCE)
SET(PLUGIN_EPHEMPROPAGATOR OFF CACHE BOOL "" FORCE)
SET(PLUGIN_EKF OFF CACHE BOOL "" FORCE)
SET(PLUGIN_ESTIMATION OFF CACHE BOOL "" FORCE)
SET(PLUGIN_EVENTLOCATOR OFF CACHE BOOL "" FORCE)
SET(PLUGIN_EXTERNALFORCEMODEL OFF CACHE BOOL "" FORCE)
SET(PLUGIN_EXTRAPROPAGATORS OFF CACHE BOOL "" FORCE)
SET(PLUGIN_FMINCONOPTIMIZER OFF CACHE BOOL "" FORCE)
SET(PLUGIN_FORMATION OFF CACHE BOOL "" FORCE)
SET(PLUGIN_GEOMETRICMEASUREMENT OFF CACHE BOOL "" FORCE)
SET(PLUGIN_GMATFUNCTION OFF CACHE BOOL "" FORCE)
SET(PLUGIN_MATLABINTERFACE OFF CACHE BOOL "" FORCE)
SET(PLUGIN_NEWPARAMETERS OFF CACHE BOOL "" FORCE)
SET(PLUGIN_POLYHEDRONGRAVITY OFF CACHE BOOL "" FORCE)
SET(PLUGIN_PRODUCTIONPROPAGATORS OFF CACHE BOOL "" FORCE)
SET(PLUGIN_PYTHONINTERFACE OFF CACHE BOOL "" FORCE)
SET(PLUGIN_SAVECOMMAND OFF CACHE BOOL "" FORCE)
SET(PLUGIN_SCRIPTTOOLS OFF CACHE BOOL "" FORCE)
SET(PLUGIN_STATION OFF CACHE BOOL "" FORCE)
SET(PLUGIN_THRUSTFILE OFF CACHE BOOL "" FORCE)
SET(PLUGIN_TLEPROPAGATOR OFF CACHE BOOL "" FORCE)
SET(PLUGIN_YUKONOPTIMIZER OFF CACHE BOOL "" FORCE)
